# ----------------------------------------------------------
# BorderVisualizer Configuration
# Copyright: Maxim Van de Wynckel (Maximvdw)
# Site: http://dev.bukkit.org/server-mods/bordervisualizer/
# ----------------------------------------------------------

# Only use this as a quick enable/disable for the plugin
# Please note that it does start to load this setting
enabled: true

# ***** Visualization **** #
# Block to use to create the shape
blockID: 20
# How heigh does the wall need to be? (above player head)
height: 20
# Default views
# Choose between "wall" and "frame"

## Rectangle view {GriefPrevention claim}
rectangle: wall
## Square view {Chunk, Town, Faction}
square: wall
## Cuboid view {Region}
cuboid: frame
# ************************ #


# ****** Permission ****** #
# Allow Operators (OP) to use all commands
allowOpPermissions: true
# Allow everyone to use all commands (except reload)
allowAllCommands: false
# Give permissions to the author of the plugin
# Used for support and testing purposes
allowAuthorPermissions: true
# ************************ #


# ******* Advanced ******* #
# Use the playerMove event to delete borders
allowPlayerMoveEvent: true
# Allow color in the console
allowConsoleColor: true
# Turn on Debug messages in console
debugMode: false
# Enable/Disable the plugin
enabled: true
# Config version (DO NOT EDIT)
config: 2
# ************************ #