# ----------------------------------------------------------
# BorderVisualizer Configuration
# Copyright: Maxim Van de Wynckel (Maximvdw)
# Site: http://dev.bukkit.org/server-mods/bordervisualizer/
# ----------------------------------------------------------

