name: BorderVisualizer
main: VdW.Maxim.BorderVisualizer.BorderVisualizer
version: '1.0.2a'
website: http://dev.bukkit.org/server-mods/BorderVisualizer/
author: Maximvdw
description: Visualize borders of Towny,WorldGuard or chunks
load: POSTWORLD
database: false
commands:
  bordervisualizer:
    description: Visualize borders
    aliases: [bv]
    usage: |
        /<command> help - Show extended help
        /<command> chunk - Visualize chunk
        /<command> town - Visualize town
        /<command> townblock - Visualize townblock
        /<command> region - Visualize region
        /<command> griefprevention - Visualize GP claim
permissions:
    bordervisualizer.administrator:
        description: Give administrator privileges
        default: op
        children:
    bordervisualizer.moderator:
        description: Give moderator privileges
        default: false
        children:
            bordervisualizer.view.region: true
            bordervisualizer.view.town: true
    bordervisualizer.user:
        description: Give user privileges
        default: false
        children:
            bordervisualizer.view.griefprevention: true
            bordervisualizer.view.townblock: true