name: BorderVisualizer
main: VdW.Maxim.BorderVisualizer.BorderVisualizer
version: '0.0.1A'
website: http://dev.bukkit.org/server-mods/BorderVisualizer/
author: Maximvdw
description: Visualize borders of Towny,WorldGuard or chunks
commands:
  bv:
    description: Visualize borders